import type { RawPoint } from "@/types/sample";
import type { TestObject, TestReport } from "@/types/testObject";

export const PDF_NOT_READY = "PDF will be regenerated by the next render call";

/** Stub — replaced by src/utils/pdfReport.tsx (React PDF). Kept to avoid stale imports. */
export async function exportReportPdf(_o: TestObject, _r: TestReport): Promise<void> {
  console.warn(PDF_NOT_READY);
}

export type { RawPoint };
