import { jsPDF } from "jspdf";
import type { TestObject, TestReport } from "@/types/testObject";

/**
 * Generate a self-contained PDF report for a tested object.
 * Renders header, object metadata, results summary, and a current-vs-time
 * line chart drawn directly from sample data (no html2canvas dependency).
 */
export function exportReportPdf(object: TestObject, report: TestReport) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();

  // Header bar
  doc.setFillColor(245, 158, 11);
  doc.rect(0, 0, pageW, 22, "F");
  doc.setTextColor(20, 20, 20);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("ELECTROSOFT AUTOMATION", 12, 10);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("Reactor Linearity Test Report", 12, 16);

  doc.setTextColor(40, 40, 40);
  doc.setFontSize(9);
  doc.text(new Date(report.completedAt).toLocaleString(), pageW - 12, 10, { align: "right" });
  const statusLabel = report.status.toUpperCase();
  doc.setFont("helvetica", "bold");
  doc.setTextColor(report.status === "passed" ? 22 : 200, report.status === "passed" ? 130 : 30, 60);
  doc.text(`Result: ${statusLabel}`, pageW - 12, 16, { align: "right" });

  // Object metadata
  let y = 32;
  doc.setTextColor(20, 20, 20);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Test Object", 12, y); y += 6;

  doc.setDrawColor(220);
  doc.line(12, y - 2, pageW - 12, y - 2);

  const rows: [string, string][] = [
    ["Serial Number", object.serialNumber],
    ["Name", object.name],
    ["Manufacturer", object.manufacturer || "—"],
    ["Rated Voltage", `${object.ratedVoltage} V`],
    ["Max Voltage", `${object.maxVoltage} V`],
    ["Rated Current", `${object.ratedCurrent} A`],
    ["Peak Current", `${object.peakCurrent} A`],
    ["Frequency", object.frequency ? `${object.frequency} Hz` : "—"],
    ["Inductance", object.inductance ? `${object.inductance} mH` : "—"],
  ];
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  rows.forEach(([k, v]) => {
    doc.setTextColor(110);
    doc.text(k, 12, y);
    doc.setTextColor(20);
    doc.setFont("helvetica", "bold");
    doc.text(v, 70, y);
    doc.setFont("helvetica", "normal");
    y += 5.5;
  });

  if (object.notes) {
    y += 2;
    doc.setTextColor(110); doc.text("Notes", 12, y);
    doc.setTextColor(20);
    const wrapped = doc.splitTextToSize(object.notes, pageW - 84);
    doc.text(wrapped, 70, y); y += wrapped.length * 5;
  }

  // Results summary
  y += 6;
  doc.setFont("helvetica", "bold"); doc.setFontSize(12);
  doc.text("Test Results", 12, y); y += 6;
  doc.line(12, y - 2, pageW - 12, y - 2);
  doc.setFontSize(10); doc.setFont("helvetica", "normal");

  const summary: [string, string][] = [
    ["Status", statusLabel],
    ["Peak Current Reached", `${report.peakCurrent.toFixed(2)} A`],
    ["Test Duration", `${report.durationS.toFixed(2)} s`],
    ["Total Samples", String(report.samples.length)],
  ];
  summary.forEach(([k, v]) => {
    doc.setTextColor(110); doc.text(k, 12, y);
    doc.setTextColor(20); doc.setFont("helvetica", "bold");
    doc.text(v, 70, y);
    doc.setFont("helvetica", "normal");
    y += 5.5;
  });

  // Graph
  y += 8;
  doc.setFont("helvetica", "bold"); doc.setFontSize(12);
  doc.text("Current vs Time", 12, y); y += 4;

  drawCurrentChart(doc, report, { x: 12, y, w: pageW - 24, h: 90 });

  // Footer
  doc.setFontSize(8); doc.setTextColor(140);
  doc.text(
    `Generated by Electrosoft Automation RLTS · Object ID ${object.id}`,
    pageW / 2, 290, { align: "center" },
  );

  doc.save(`Report_${object.serialNumber}_${report.status}.pdf`);
}

function drawCurrentChart(
  doc: jsPDF,
  report: TestReport,
  box: { x: number; y: number; w: number; h: number },
) {
  const { x, y, w, h } = box;
  const samples = report.samples;
  if (samples.length < 2) {
    doc.setFontSize(10); doc.setTextColor(150);
    doc.text("No data captured.", x + w / 2, y + h / 2, { align: "center" });
    return;
  }

  // Frame
  doc.setDrawColor(210);
  doc.setLineWidth(0.2);
  doc.rect(x, y, w, h);

  const tMax = samples[samples.length - 1].time || 1;
  const iMax = Math.max(...samples.map((s) => s.current), 0.01);

  // Grid + axis labels
  const ticks = 5;
  doc.setFontSize(7); doc.setTextColor(130);
  for (let i = 0; i <= ticks; i++) {
    const gy = y + (h * i) / ticks;
    doc.setDrawColor(235);
    doc.line(x, gy, x + w, gy);
    const val = iMax * (1 - i / ticks);
    doc.text(val.toFixed(1), x - 2, gy + 1.5, { align: "right" });
  }
  for (let i = 0; i <= ticks; i++) {
    const gx = x + (w * i) / ticks;
    doc.setDrawColor(235);
    doc.line(gx, y, gx, y + h);
    const val = (tMax * i) / ticks;
    doc.text(`${val.toFixed(2)}s`, gx, y + h + 4, { align: "center" });
  }

  // Curve
  doc.setDrawColor(234, 88, 12);
  doc.setLineWidth(0.5);
  let prev: { px: number; py: number } | null = null;
  for (const s of samples) {
    const px = x + (s.time / tMax) * w;
    const py = y + h - (s.current / iMax) * h;
    if (prev) doc.line(prev.px, prev.py, px, py);
    prev = { px, py };
  }

  // Axis titles
  doc.setFontSize(8); doc.setTextColor(60);
  doc.text("Current (A)", x + 2, y - 1);
  doc.text("Time (s)", x + w, y + h + 8, { align: "right" });
}
